"""фикс удаления аккаунта

Revision ID: 65a31ed8add9
Revises: a6dfe50e97ae
Create Date: 2025-07-22 22:10:02.992502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a31ed8add9'
down_revision: Union[str, Sequence[str], None] = 'a6dfe50e97ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'steam_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'steam_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
