from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '65a31ed8add9'
down_revision = 'a6dfe50e97ae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Для SQLite: пересоздаем таблицу с нужной структурой
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('steam_id',
            existing_type=sa.String(length=32),
            nullable=True
        )
    # ### end Alembic commands ###

def downgrade():
    # Возвращаем обратно NOT NULL
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('steam_id',
            existing_type=sa.String(length=32),
            nullable=False
        )